version: "3"

services:
  database:
    image: "postgres:13-alpine"
    environment: 
      POSTGRES_USER: "cours"
      POSTGRES_DB: "cours"
      POSTGRES_PASSWORD: "cours"
    volumes:
      - "cours:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  application: 
    image: "eventown:latest"
    command: "node ./back/index.js"
    ports:
      - 3000:3000

volumes: 
  cours: